src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    #[ORM\OneToMany(targetEntity: 'Discussions', mappedBy: 'Use', fetch:"EXTRA_LAZY", cascade:['persist', 'remove'])]
    protected $Discussions;

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Pseudo = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Nom = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Prenom = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Age = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Telephone = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Ville = null;

    #[ORM\Column(type: 'boolean')]
    private $isVerified = false;

    #[ORM\Column(nullable: true)]
    private ?\DateTime $lastActivityAt ;

    public function __construct()
    {
        $this->Discussions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getPseudo(): ?string
    {
        return $this->Pseudo;
    }

    public function setPseudo(string $Pseudo): self
    {
        $this->Pseudo = $Pseudo;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(string $Prenom): self
    {
        $this->Prenom = $Prenom;

        return $this;
    }

    public function getAge(): ?string
    {
        return $this->Age;
    }

    public function setAge(string $Age): self
    {
        $this->Age = $Age;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->Telephone;
    }

    public function setTelephone(string $Telephone): self
    {
        $this->Telephone = $Telephone;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->Ville;
    }

    public function setVille(string $Ville): self
    {
        $this->Ville = $Ville;

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }


    public function setLastActivityAt($lastActivityAt): self
    {
        $this->lastActivityAt = $lastActivityAt;

        return $this;
    }

    public function getLastActivityAt(): \DateTime
    {
        return $this->lastActivityAt;
    }

    public function isActiveNow(): bool
    {
        // Delay during wich the user will be considered as still active
        $delay = new \DateTime('2 minutes ago');

        return ( $this->getLastActivityAt() > $delay );
    }

    public function isIsVerified(): ?bool
    {
        return $this->isVerified;
    }

    /**
     * @return Collection<int, Discussions>
     */
    public function getDiscussions(): Collection
    {
        return $this->Discussions;
    }

    public function addDiscussion(Discussions $discussion): self
    {
        if (!$this->Discussions->contains($discussion)) {
            $this->Discussions->add($discussion);
            $discussion->setUser($this);
        }

        return $this;
    }

    public function removeDiscussion(Discussions $discussion): self
    {
        if ($this->Discussions->removeElement($discussion)) {
            // set the owning side to null (unless already changed)
            if ($discussion->getUser() === $this) {
                $discussion->setUser(null);
            }
        }

        return $this;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %} - PROJET FORUM - {% endblock %}</title>

            <meta charset="UTF-8">
            <meta http-equiv="X-UA-Compatible" content="IE=edge">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">

        {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
            <link rel="stylesheet" href="{{ asset('style.css') }}">
            <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
            <link rel="stylesheet" href="http://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
            <link rel="stylesheet" href="//code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">
            <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css">
            <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css">
            <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/jq-3.2.1/dt-1.10.16/datatables.min.css"/>
            <link rel="stylesheet"
                  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css">

        {% endblock %}



        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
{#            <script src="https://code.jquery.com/jquery-3.6.1.js" integrity="sha256-3zlB5s2uwoUzrXK3BT7AX3FyvojsraNFxCc2vC/7pNI=" crossorigin="anonymous"></script>#}

{#            <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js" integrity="sha256-xLD7nhI62fcsEZK2/v8LsBcb4lG7dgULkuXoXB/j91c=" crossorigin="anonymous"></script>#}
{#            <script src="http://code.jquery.com/jquery-1.9.1.js"></script>#}
{#            <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>#}

{#            <script src="http://code.jquery.com/ui/1.11.4/jquery-ui.js"></script>#}
{#            <script src="https://code.jquery.com/jquery-3.6.0.js"></script>#}
{#            <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>#}
{#            <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>#}
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"></script>
        {% endblock %}

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>

        <script src="{{ asset('bundles/datatables/js/datatables.js') }}"></script>
        <script type="text/javascript" src="https://cdn.datatables.net/v/dt/jq-3.2.1/dt-1.10.16/datatables.min.js"></script>


    </head>

<body id="body-pd">
    <header class="header" id="header">
        <div class="header_toggle"> <i class='bx bx-menu' id="header-toggle"></i> </div>
        <div class="number_of_connected"> <i class='bx bxs-user-badge'></i> <p id="pers_textr"> Numbers of connected : </p><p id="pers"> 0 </p> </div>
    </header>
    <div class="l-navbar" id="nav-bar">
        <nav class="nav">
            <div> <a href="{{ path('app_login') }}" class="nav_logo"> <i class='bx bx-layer nav_logo-icon'></i> <span class="nav_logo-name">

                        {% if app.user.email is defined %}
                        <span class="name">{{ app.user.pseudo }}</span>
                        {% else %}
                        <span class="name" style="font-size: 14px">You'r not connected!</span>
                        {% endif %}</span> </a>

                <div class="nav_list">
                    <a href="{{ path('forum_theme') }}" class="nav_link"> <i class='bx bx-grid-alt nav_icon'></i> <span class="nav_name">Forum</span> </a>
                    {% if app.user.roles.0 is defined %}
                        <a href="{{ path('user_informations') }}" class="nav_link"> <i class='bx bx-user nav_icon'></i> <span class="nav_name">My informations</span> </a>
                        {% if app.user.roles is defined and app.user.roles.0 == "ROLE_ADMIN" %}
                        <a href="{{ path('new_theme') }}" class="nav_link"> <i class='bx bx-bookmark nav_icon'></i> <span class="nav_name">Themes</span> </a>
                        <a href="{{ path('user-list') }}" class="nav_link"> <i class='bx bx-list-ul nav_icon'></i> <span class="nav_name">Users</span> </a> </div>
                        {% endif %}
                    {% endif %}


            </div> <a href="{{ path('app_logout') }}" class="nav_link"> <i class='bx bx-log-out nav_icon'></i> <span class="nav_name">Log out ...</span> </a>
        </nav>
    </div>
    <!--Container Main start-->
    <div class="height-100 bg-light">

        <h1 class="PageTitle">{% block Titlebody %} {% endblock %}</h1>
        <div class="DivContainer">{% block body %}{% endblock %}</div>

    </div>

    <script
            src="https://code.jquery.com/jquery-3.6.0.min.js"
            integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
            crossorigin="anonymous"
    ></script>
    <script type="text/javascript" src="https://cdn.datatables.net/v/dt/jq-3.2.1/dt-1.10.16/datatables.min.js"></script>

    <!-- ✅ load jQuery UI ✅ -->
    <script
            src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"
            integrity="sha512-uto9mlQzrs59VwILcLiRYeLKPPbS/bT71da/OEBYEwcdNUk8jYIy+D176RYoop1Da+f9mvkYrmj5MCLZWEtQuA=="
            crossorigin="anonymous"
            referrerpolicy="no-referrer"
    ></script>
            {% block JSAfterBody %}

            {% endblock %}
    <script>
            /* --- Menu --- */
            document.addEventListener("DOMContentLoaded", function(event) {

                const showNavbar = (toggleId, navId, bodyId, headerId) =>{
                    const
                        toggle = document.getElementById(toggleId),
                        nav = document.getElementById(navId),
                        bodypd = document.getElementById(bodyId),
                        headerpd = document.getElementById(headerId)

                    if(toggle && nav && bodypd && headerpd){
                        toggle.addEventListener('click', ()=>{
                            nav.classList.toggle('show')
                            toggle.classList.toggle('bx-x')
                            bodypd.classList.toggle('body-pd')
                            headerpd.classList.toggle('body-pd')
                        })
                    }
                }
                showNavbar('header-toggle','nav-bar','body-pd','header')
            });

            /* --- Appel AJAX pour avoir le nombre de personne connecté --- */
            $(document).ready(function(){
                ConnectedPerson();
            });

            /* --- Fonction pour avoir le nombre de personne connecté --- */
            function ConnectedPerson()
            {
                $.ajax({
                    url: '/number_of_connected',
                    success: function(data, status)
                    {
                            console.log("Connected person : " + data);
                            $("#pers").replaceWith("<p id='pers'>" + data + "</p>");
                            setTimeout(function(){ConnectedPerson();}, 2000);
                    },
                    async:   true
                });
            }
        </script>

        <script>

            /* --- Fonction pour avoir l'auto complete des villes --- */

            {% if MonTabDeVille is not defined %}
            {% set MonTabDeVille = "" %}
            {% endif %}

            $( function() {
               var availableTags = {{ MonTabDeVille|raw }}
                   $( "#modify_form_form_ville" ).autocomplete({
                       source: availableTags
                   });
            } );

            $(document).on('click','.delete_comm',function (e){
                if(!confirm('Do you really want to delete this comment ?')){
                    e.stopPropagation();
                    e.stopImmediatePropagation();
                    e.preventDefault();

                }
            })

            $(document).on('click','.modify_comm',function (e){

                console.log($(this).attr('data-id'));
                $('#modifyComment').val($(this).attr('data-comment'));
                $('#modifyComment').attr('data-id',$(this).attr('data-id'));


            });

            $(document).on('click','#saveChange',function (e){
                let com = $('#modifyComment').val();
                let id = $('#modifyComment').attr('data-id');

                $.ajax({
                    url: '/update_comment',
                    data:{
                        id: id,
                        comment: com
                    },
                    success: function()
                    {
                        location.reload();
                    }
                });
            })


        </script>


    <script src="{{ asset('bundles/datatables/js/datatables.js') }}"></script>

    {% block data_tables %} {% endblock %}





</body>
</html>

templates/forum_theme.html.twig
{% extends 'base.html.twig' %}

{% block title %} List of themes !{% endblock %}

{% block Titlebody %}List of themes {% endblock %}

{% block body %}

    <button type='button' style="opacity: 0" class='btn btn-primary' id="loader" data-bs-toggle='modal' data-bs-target='#exampleModal'> </button>
    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel"></h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <p> Loading ... </p>
                </div>
                <div class="modal-footer">
                    <button type="button" style="opacity: 0" id="removeLoader" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>


    <div class="Contain50">
        <h3> Choose a theme and go ! </h3>
        <hr>
        <div id="Datatable">Loading...</div>

    </div>



    {% block data_tables %}
        {% if datatableTheme is defined %}

            <script>
                $('#loader').trigger('click');

                function removeLoader(){
                    $('#removeLoader').trigger('click');

                }

                function lastComment() {
                    $( ".lastComment" ).each(function( index ) {
                        let here = $(this);
                        $.ajax({
                            url: '/last_comment',
                            data:{
                              idTheme : $( this ).attr('data-id'),
                            },
                            success: function(data, status)
                            {
                                here.replaceWith("<p> " + data.data + "</p>");
                            },
                            async: false,
                        });
                    });
                    setTimeout(function(){lastComment();}, 200000);
                }

                function numberOfComment() {
                    $(".numberOfComment").each(function (index) {
                        let here = $(this);
                        $.ajax({
                            url: '/number_of_comment',
                            data: {
                                idTheme: $(this).attr('data-id'),
                            },
                            success: function (data, status) {
                                here.replaceWith("<p> " + data.data[0][1] + "</p>");
                            },
                            async: false,
                        });
                    });
                    setTimeout(function(){numberOfComment();}, 200000);
                }

                $(function() {
                    $('#Datatable').initDataTables({{ datatable_settings(datatableTheme) }},
                        {
                            "pageLength": 5,
                            "serverSide": false,
                            "lengthMenu": [5, 10, 25, 50, 100],
                            columnDefs: [
                                {width: "60%", targets: 0},
                                {width: "20%", targets: 1},
                                {width: "20%", targets: 2},
                            ],
                            "initComplete":function( settings, json){
                                lastComment();
                                numberOfComment();
                                removeLoader();
                            }
                        } );
                });



            </script>

        {% endif %}
    {% endblock %}

{% endblock %}

templates/new_discussions.html.twig
{#{% extends 'base.html.twig' %}#}

{#{% block title %}New discussions{% endblock %}#}

{#{% block Titlebody %} New discussions {% endblock %}#}

{#{% block body %}#}
{#    {% for flash_error in app.flashes('verify_email_error') %}#}
{#        <div class="alert alert-danger" role="alert">{{ flash_error }}</div>#}
{#    {% endfor %}#}
<div class="Contain50" >
    {{ form_start(newDiscussions) }}
        {{ form_row(newDiscussions.Contenu) }}

        <button type="submit" class="btn btn-primary">Save</button>
    {{ form_end(newDiscussions) }}
</div>


{#{% endblock %}#}

templates/theme.html.twig
{% extends 'base.html.twig' %}

{% block title %} Theme : {{ theme }} {% endblock %}

{% block Titlebody %} Theme : {{ theme }} {% endblock %}

{% block body %}
    <div class="Contain100">
        <h3> Let's talk about  {{ theme }} ! </h3>
        <hr>
        <div id="Datatable">Loading...</div>

    </div>


    {% block data_tables %}
        {% if datatableDiscussions is defined %}
        <script>
            $(function() {
                $('#Datatable').initDataTables({{ datatable_settings(datatableDiscussions) }},
                    {
                        "lengthMenu": [10, 25, 50, 100],

                        columnDefs: [
                            {width: "55%", targets: 0},
                            {width: "12%", targets: 1},
                            {width: "12%", targets: 2},
                            {width: "7%", targets: 3},
                        ]
                    } );
            });

        </script>
        {% endif %}
    {% endblock %}

{% if app.user.roles is defined %}
    <div class="" style="margin-bottom: 20px">
    <div id="open" class="open btn btn-primary" style="margin-bottom: 10px"> Let's add new comment ! </div>
{#    <div id="close"> <i class="fa-solid fa-xmark"></i> </div>#}
    {{ render(controller('App\\Controller\\ForumController::newDiscussions', {'theme': theme, 'request': app.request } )) }}
    </div>

{% endif %}

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Update comment !</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <textarea maxlength="5000" style="width: 100%" name="modifyComment" id="modifyComment"> </textarea>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" id="saveChange">Save changes</button>
                </div>
            </div>
        </div>
    </div>

{% endblock %}
{% block JSAfterBody %}

    <script>
        /* --- Fonction pour faire apparaitre / disparaitre la section new comment --- */
        $('.Contain50').hide();

    $('#open').on('click',function(e){
        if ($('.Contain50').is(":visible"))   {
            $('.Contain50').hide('fast');
            $('#new_discussions_Contenu').val('');
            $('#open').html("Let's add new comment !");

        }else {
            $('.Contain50').show('fast');
            $('#open').html("<i class='fa-solid fa-chevron-up'></i>");
        }
    })




    </script>

{% endblock %}

templates/user-list.html.twig
{% extends 'base.html.twig' %}
{% block title %} User's list !{% endblock %}

{% block Titlebody %}User's list {% endblock %}

{% block body %}
    <div class="Contain50">
        <h3> Users </h3>
        <hr>
    <div id="Datatable">Loading...</div>

    </div>




    {% block data_tables %}
        {% if datatableUserList is defined %}
            <script>
                $(function() {
                    $('#Datatable').initDataTables({{ datatable_settings(datatableUserList) }},
                        {
                            "pageLength": 10,
                            columnDefs: [
                                {width: "8%", targets: 0},
                            ]
                        } );
                });

            </script>
        {% endif %}
    {% endblock %}

{% endblock %}